In [1]:
import math
import numpy as np
from pyscf import gto, scf, mp
from pyscf.geomopt.berny_solver import optimize

mol = gto.M(atom='''
O
H 1 1.0;
H 1 1.0 2 120.0;
''',
basis='ccpvdz', unit='Angs', charge=0, verbose=0)
#10^(-10)m = 0.1

hf = scf.RHF(mol)
thresh = {
    'gradientmax':1e-3, #Eh/AA
    'gradientrms':1e-4, #Eh/AA
    'stepmax':1e-2, #AA
    'steprms':1e-3, #AA
}
print(f'Initial geometry = \n{mol.atom_coords()}\n')

Initial geometry = 
[[ 0.          0.          0.        ]
 [ 1.88972612  0.          0.        ]
 [-0.94486306  0.          1.63655083]]



In [2]:
mol = optimize(hf, **thresh,verbose=3)
print(f'Optimized geometry = \n{mol.atom_coords()}\n')


Geometry optimization cycle 1
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   O   0.000000   0.000000   0.000000    0.000000  0.000000  0.000000
   H   1.000000   0.000000   0.000000    0.000000  0.000000  0.000000
   H  -0.500000   0.000000   0.866025    0.000000  0.000000  0.000000
cycle 1: E = -76.0142704702  dE = -76.0143  norm(grad) = 0.0901091

Geometry optimization cycle 2
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   O  -0.018963   0.000000  -0.032846   -0.018963  0.000000 -0.032846
   H   0.916420   0.000000   0.070152   -0.083580  0.000000  0.070152
   H  -0.397457   0.000000   0.828719    0.102543  0.000000 -0.037306
cycle 2: E = -76.0268051554  dE = -0.0125347  norm(grad) = 0.0160249

Geometry optimization cycle 3
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   O  -0.025890   0.000000  -0.044843   -0.006927  0.000000 

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyscf/lib/chkfile.py:165: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  mol = gto.loads(fh5['mol'].value)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyscf/lib/chkfile.py:71: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  return val.value


cycle 3: E = -76.0270522047  dE = -0.000247049  norm(grad) = 0.00167964

Geometry optimization cycle 4
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   O  -0.026194   0.000000  -0.045369   -0.000304  0.000000 -0.000526
   H   0.911684   0.000000   0.081235    0.000482  0.000000  0.000072
   H  -0.385490   0.000000   0.830159   -0.000179  0.000000  0.000454
cycle 4: E = -76.0270534857  dE = -1.28099e-06  norm(grad) = 0.000205084

Geometry optimization cycle 5
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   O  -0.026201   0.000000  -0.045382   -0.000007  0.000000 -0.000013
   H   0.911565   0.000000   0.081312   -0.000119  0.000000  0.000077
   H  -0.385364   0.000000   0.830094    0.000127  0.000000 -0.000065
cycle 5: E = -76.0270535127  dE = -2.69661e-08  norm(grad) = 4.94336e-06
Optimized geometry = 
[[-0.0495128   0.         -0.08575868]
 [ 1.72260779  0.          0.15365827]
 [-0.7